@startuml
title Query I-Score

participant "ICON Service engine" as IS
participant "IISS engine" as IISS
database "state DB" as SDB
database "IISS data" as ID
participant "Reward Calculator" as RC
database "I-Score DB" as ISDB

-> IS: [mq] query
IS -> IISS: [call] query
IISS -> RC: [mq] query
RC -> ISDB: read I-Score
opt old I-Score
RC -> RC: caculate I-Score
RC -> ISDB: write I-Score
end
RC -> IISS: [mq] query response
IISS -> IS: return response

newpage Claim I-Score

group block invoke

-> IS: [mq] block invoke
IS -> IISS: [call] with TX
IISS -> RC: [mq] claim
RC -> ISDB: read I-Score
opt old I-Score
RC -> RC: caculate I-Score
end
RC -> IISS: claim response
IISS -> IS: return response

end

group write_precommit_state, remove_precommit_state

-> IS: [mq] write_precommit_state\nor remove_precommit_state
IS -> IISS: commit or rollback
IISS -> RC: [mq] commit or rollback
alt commit
RC -> ISDB: set I-Score 0 and \nupdate block height
else rollback
RC -> RC: reset memory
end
RC -> IISS: [mq] commit or rollback response
opt commit
IISS -> SDB: update ICX
end
IISS -> IS: return response

end

@enduml
